### ISSUE TITLE
Does it support 13th generation processor?

### ISSUE THREAD

**Issue by devchenli** [likidu/OpenCore-ASRock-B660m-ITX-AC#1]
Hello，Does it support 13th generation processor?

**Comment by likidu** [comment]
The motherboard sure supports 13th Intel. But you might need to modify the `config.plist` for your specific processor which I did not have a chip to test with.

Here is some latest up to date (OpenCore v0.9.5) EFI repo you can check: https://github.com/luchina-gabriel/BASE-EFI-INTEL-DESKTOP-13THGEN-RAPTOR-LAKE
